### ISSUE TITLE
$gsap is of type unknown?

### ISSUE THREAD

**Issue by torstah** [hypernym-studio/nuxt-gsap#51] opened 2023-09-06 14:07 UTC
### Steps to Reproduce

Hey 

Followed the install instructions. Everything works, but there are no types. Anything I'm missing? 

### Current Behavior

No types

### Expected Behavior

Should have types

**Comment by ivodolenc** [comment] 2023-09-07 08:11
Hi, I just tested it (followed official docs) and the module works fine, the types are imported as expected.

#### Example

```html
<template>
  <div>
    <h1 class="title">Nuxt Gsap</h1>
  </div>
</template>

<script setup lang="ts">
  const { $gsap } = useNuxtApp()

  onMounted(() => {
    $gsap.to('.title', { rotation: 3, x: 100, duration: 1 })
  })
</script>
```

<img width="467" alt="" src="https://github.com/hypernym-studio/nuxt-gsap/assets/51852491/b4710aca-f27e-48fb-871e-7ccc3439df7f">
<img width="461" alt="" src="https://github.com/hypernym-studio/nuxt-gsap/assets/51852491/1725b251-1a8e-417e-8661-46c601d5421b">



#### Versions

- nuxt: `3.7.0`
- @hypernym/nuxt-gsap: `2.2.2`

**Comment by torstah** [comment] 2023-09-07 16:47
Thanks.

Very strange indeed. I’ve tried reinstalling, deleted both node_modules and
.Nuxt folder

Any hints?

tors 7 sep. 2023 kl. 10:11 skrev Ivo Dolenc ***@***.***>:

**Comment by ivodolenc** [comment] 2023-09-07 17:05
Sorry, I can't help you without a reproduction. Feel free to provide an example repo if you find any issues.

I'm closing this as resolved since no code has been shared that indicates the problem.

**Closed by ivodolenc** 2023-09-07 17:05 UTC

**Comment by klren0312** [comment] 2023-09-27 08:53
I also have this problem
![1695804799583](https://github.com/hypernym-studio/nuxt-gsap/assets/10903843/43bd5fca-7931-41c0-aba3-7c39cb6259d5)

**Comment by ivodolenc** [comment] 2023-09-27 09:21
Hi @klren0312, can you provide more information? It would be best if you could share a link to a minimal reproduction on github, codesandbox etc so I can see where the problem is. Without seeing the code I can't help much.

Have you tried deleting the `node_modules` and `.nuxt` directory and reinstalling the dependencies as [mentioned](https://github.com/hypernym-studio/nuxt-gsap/issues/51#issuecomment-1710481683) above?

**Comment by klren0312** [comment] 2023-09-28 07:56
> Hi @klren0312, can you provide more information? It would be best if you could share a link to a minimal reproduction on github, codesandbox etc so I can see where the problem is. Without seeing the code I can't help much.
> 
> Have you tried deleting the `node_modules` and `.nuxt` directory and reinstalling the dependencies as [mentioned](https://github.com/hypernym-studio/nuxt-gsap/issues/51#issuecomment-1710481683) above?

not work
I create the new project,  it also not work
and in `.nuxt/gsapPlugin.d.ts`, `Cannot find module '#app'`
![image](https://github.com/hypernym-studio/nuxt-gsap/assets/10903843/77802e8e-e1fe-4aa4-95a2-f2337b7808ce)

![image](https://github.com/hypernym-studio/nuxt-gsap/assets/10903843/c2822c39-7ac9-4da8-af2c-1d74fe3d01d6)

this is my project link https://github.com/klren0312/gsapproblem

**Comment by ivodolenc** [comment] 2023-09-28 11:40
@klren0312  Thanks for the link, this was really helpful.

The repo works as expected for me.

<img width="854" alt="" src="https://github.com/hypernym-studio/nuxt-gsap/assets/51852491/4a9c36c1-c21f-4cdd-94a5-0db37d752429">

<img width="845" alt="" src="https://github.com/hypernym-studio/nuxt-gsap/assets/51852491/d23339c8-7f00-4649-accc-ffb274986d53">

<img width="902" alt="" src="https://github.com/hypernym-studio/nuxt-gsap/assets/51852491/c1818216-57dd-4a39-b59c-f1b7e42a3ec2">

<img width="1109" alt="" src="https://github.com/hypernym-studio/nuxt-gsap/assets/51852491/bf0f6ab5-83f3-4d9d-a31b-4061cc498165">





### Here are the steps I took:

1. Download the [repo](https://github.com/klren0312/gsapproblem) from Github.
2. Open VSCode, drag the repo folder to the editor.
3. Run `npm i` command to install all dependencies.
   - (Nuxt will automatically generate the `.nuxt` dir because the package has a `postinstall` script defined)
4. Optionally, run `npm run dev` to open the dev server.

---

Try a few more times, sometimes it can be something very simple like restarting the VSCode editor or maybe just restarting the TypeScript server inside VSCode etc.

Also, delete and reinstall the node_modules and .nuxt directories.

I know this can be stressful, but right now this is the price for auto-generated types in complex projects/frameworks, it can very easily get complicated where it shouldn't be.

---

Feel free to open a new issue if it still occurs.

**Comment by klren0312** [comment] 2023-10-16 06:45
![image](https://github.com/hypernym-studio/nuxt-gsap/assets/10903843/6cb10721-515e-426a-b8c0-c8165e3139ef)
 It works today,  maybe the editor problem
